In [16]:
import numpy as np
import pandas as pd
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("a:",a, a.shape)
b= a.T
print("b:", b)
c = a.T.dot(a)
d = a.T * a
print("c:", c)
print("d:", d)

e = a * a
print("e:", e)


matrix = pd.DataFrame([[1, 2, 3], [4, 5, 6]], index=['row1', 'row2'], columns=['col1', 'col2', 'col3'])
print(matrix)
m_b = matrix.T
print(m_b, m_b.shape)

a: [[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
b: [[1 4 7]
 [2 5 8]
 [3 6 9]]
c: [[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]
d: [[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]
e: [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
      col1  col2  col3
row1     1     2     3
row2     4     5     6
      row1  row2
col1     1     4
col2     2     5
col3     3     6 (3, 2)


In [ ]:
import matplotlib.pyplot as plt
plt.